version: "3.9"
services:
  backend:
    command: npx nodemon server.js --watch .
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/usr/src/app
  frontend:
    command: npm start
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
